import os

file_path = 'lib/core/data/quiz_data.dart'

with open(file_path, 'r', encoding='utf-8') as f:
    content = f.read()

# Verify that the closing bracket of the list is at the very end
if not content.strip().endswith('];'):
    print("Error: File does not end with '];'")
    exit(1)

# Let's define the 60 questions for Konuk Giriş Çıkış İşlemleri
new_questions = """
  // ==========================================
  // DERS: KONUK GİRİŞ ÇIKIS İŞLEMLERİ (60 Soru)
  // ==========================================
  // ÜNİTE 1: ODA SATIŞ TEKNİKLERİ (15 Soru)
  QuizQuestion(id: 'kgc10_1_1', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Otel işletmelerinde en yüksek gelir payına sahip olan, adeta işletmenin şah damarı olarak nitelendirilen departman veya hizmet hangisidir?',
    options: ['Yiyecek İçecek Hizmetleri', 'Oda Satış ve Konaklama Hizmetleri', 'Animasyon ve Eğlence', 'Satın Alma ve Depolama'],
    correctOptionIndex: 1,
    explanation: 'Otel işletmelerinde toplam gelirlerin %60 ile %80 arasındaki en büyük kısmı oda satışlarından elde edilir.',
  ),
  QuizQuestion(id: 'kgc10_1_2', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Misafirle ilk karşılaşmada, olumlu veya olumsuz yargıların şekillendiği "ilk izlenim" süresi ortalama ne kadardır?',
    options: ['İlk 3 saniye', 'İlk 30 dakika', 'Giriş gününün tamamı', 'İlk 1 saat'],
    correctOptionIndex: 0,
    explanation: 'Misafirle ilk karşılaşmadaki ilk 3 saniye ilk izlenim süresidir; profesyonel duruş ve güler yüz bu sürede çok önemlidir.',
  ),
  QuizQuestion(id: 'kgc10_1_3', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Otele önceden rezervasyon yaptırmadan, doğrudan kapıdan girerek oda kiralayan misafir tipine ne ad verilir?',
    options: ['VIP Konuk', 'No-Show Konuk', 'Walk-in Konuk', 'Repeat Guest'],
    correctOptionIndex: 2,
    explanation: 'Otele rezervasyonsuz olarak, kapıdan doğrudan girerek oda talep eden misafir tipine Walk-in denir.',
  ),
  QuizQuestion(id: 'kgc10_1_4', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Misafirin ayırtmış olduğu oda tipinden daha üst segmentteki ve daha konforlu bir odayı, aradaki avantajları anlatarak satmaya ne denir?',
    options: ['Up-selling (Üst Sınıf Satış)', 'Cross-selling (Çapraz Satış)', 'Downgrade', 'Lost & Found'],
    correctOptionIndex: 0,
    explanation: 'Misafiri aradaki konfor ve fiyat farkını anlatarak daha üst sınıf bir odaya ikna etme işlemine Up-selling denir.',
  ),
  QuizQuestion(id: 'kgc10_1_5', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Oda satışının yanında oteldeki ek gelir getiren birimleri (SPA, A la Carte restoran, turlar) misafire tanıtmaya ve satmaya ne denir?',
    options: ['Up-selling', 'Cross-selling (Çapraz Satış)', 'Blokaj', 'Voucher Kontrolü'],
    correctOptionIndex: 1,
    explanation: 'Oda satışı haricinde otelin diğer gelir getiren hizmetlerinin misafire satılması işlemine Cross-selling denir.',
  ),
  QuizQuestion(id: 'kgc10_1_6', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Oda satarken misafire metrekare veya duvar rengi yerine o odada kalacağı süre boyunca elde edeceği huzur, manzara ve konforu hissettirerek satmaya ne denir?',
    options: ['Teknik Sunum', 'Fayda Odaklı Sunum', 'Fiyat Odaklı Sunum', 'Klasik Sunum'],
    correctOptionIndex: 1,
    explanation: 'Misafire fiziksel özelliklerden ziyade yaşayacağı deneyim ve konforu sunmaya Fayda Odaklı Sunum denir.',
  ),
  QuizQuestion(id: 'kgc10_1_7', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Misafirin oda fiyatını yüksek bulması (fiyat itirazı) durumunda resepsiyonist nasıl yaklaşmalıdır?',
    options: ['Hemen indirim yapmalıdır.', 'Savunmaya geçip sessiz kalmalıdır.', 'Fiyata dahil olan ücretsiz ek hizmetleri (Wi-Fi, kahvaltı, havuz vb.) ve değerini sakinlikle açıklamalıdır.', 'Misafiri diğer otele yönlendirmelidir.'],
    correctOptionIndex: 2,
    explanation: 'Fiyat itirazını yönetmede en doğru yol, fiyata dahil olan hizmetleri açıklayarak fiyatın karşılığını göstermektir.',
  ),
  QuizQuestion(id: 'kgc10_1_8', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Satış görüşmesinin son aşaması olan ve misafirin kararsızlığını gidererek oda satışını resmiyete kavuşturmaya ne denir?',
    options: ['Açılış', 'Giriş Hazırlığı', 'Satış Kapama (Closing)', 'Rezervasyon Kaydı'],
    correctOptionIndex: 2,
    explanation: 'Görüşmenin sonlandırılıp onay alınarak oda anahtarı hazırlama aşamasına geçilmesine Satış Kapama denir.',
  ),
  QuizQuestion(id: 'kgc10_1_9', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Ön büro departmanının günlük olarak hazırladığı; satılan oda sayısı, toplam ciro ve ortalama oda fiyatını (ADR) gösteren tablolara ne denir?',
    options: ['Grup Memorandumu', 'Lost & Found Defteri', 'Oda Satış Raporları', 'Kayıt Kartı Arşivi'],
    correctOptionIndex: 2,
    explanation: 'Ön büro finansal takibini sağlamak amacıyla oda satış raporlarını günlük olarak hazırlar.',
  ),
  QuizQuestion(id: 'kgc10_1_10', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Daha yüksek satış başarısı için bir resepsiyonistin beden dili nasıl olmalıdır?',
    options: ['Kolları bağlı ve ciddiyetle durmalıdır.', 'Göz teması kuran, dik bir duruşa sahip ve içten bir tebessüm sergileyen yapıda olmalıdır.', 'Sürekli bilgisayara bakmalıdır.', 'Misafire arkasını dönmelidir.'],
    correctOptionIndex: 1,
    explanation: 'Güler yüzlü ve göz teması kuran profesyonel beden dili güven vererek satışı kolaylaştırır.',
  ),
  QuizQuestion(id: 'kgc10_1_11', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Yolda arabası bozulan ve gece geç saatte otele gelen bir "Walk-in" aileye resepsiyonist nasıl yaklaşmalıdır?',
    options: ['Doğrudan en yüksek liste fiyatını söyleyip kesip atmalıdır.', 'Yorgunluklarını dikkate alarak dinlenme ihtiyacını ve odanın konforunu vurgulamalıdır.', 'Otelde yer olmadığını söyleyip göndermelidir.', 'Sadece en ucuz odayı önermelidir.'],
    correctOptionIndex: 1,
    explanation: 'Walk-in misafirlerde yorgunluk ve ihtiyaç durumuna göre empati kurup faydayı vurgulamak satışı kapatır.',
  ),
  QuizQuestion(id: 'kgc10_1_12', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Aşağıdakilerden hangisi üst sınıf satışın (up-selling) otel işletmesine sağladığı birincil faydadır?',
    options: ['Personel sayısını azaltmak', 'Oda fiyat ortalamalarını ve dolayısıyla otel oda gelirlerini artırmak', 'Temizlik süresini kısaltmak', 'Acente komisyonlarını artırmak'],
    correctOptionIndex: 1,
    explanation: 'Mevcut misafire aradaki farkla daha üst oda satılması, ekstra pazarlama maliyeti olmadan oda gelirlerini artırır.',
  ),
  QuizQuestion(id: 'kgc10_1_13', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Resepsiyonist Emre\'nin odaya giriş yapan misafire yorgunluğunu gidermek için SPA\'daki masaj indirimini sunması hangi satış türüdür?',
    options: ['Downgrade', 'Up-selling', 'Cross-selling (Çapraz Satış)', 'Stop Sales'],
    correctOptionIndex: 2,
    explanation: 'Oda haricindeki diğer departman hizmetlerinin (SPA, restoran vb.) satılması çapraz satıştır.',
  ),
  QuizQuestion(id: 'kgc10_1_14', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Misafirin "Diğer otellerde fiyatlar daha ucuz" itirazına karşı en profesyonel yanıt hangisidir?',
    options: ['"Bizim otelimiz çok lükstür efendim, ucuz yerler kalitesizdir."', '"Haklısınız efendim, ancak bizim fiyatımıza zengin açık büfe kahvaltı ve SPA kullanımı dahildir; diğerinde ise bunlar ekstradır" şeklinde değer katmak.', '"İsterseniz oraya gidebilirsiniz efendim."', 'Sessiz kalıp odayı satmamak.'],
    correctOptionIndex: 1,
    explanation: 'Fiyat itirazına karşı otelin sunduğu ek faydaları netleştirerek değer katmak en profesyonel yaklaşımdır.',
  ),
  QuizQuestion(id: 'kgc10_1_15', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 0,
    questionText: 'Otelcilikte satılmayan bir odanın gelirinin ertesi gün iki kez satılarak telafi edilememesi, otel odasının hangi özelliğindendir?',
    options: ['Çok pahalı olmasından', 'Stoklanamaz ve depolanamaz (hizmetin dayanıksızlığı) özelliğinden', 'Sadece yazın satılmasından', 'Her gün değişmesinden'],
    correctOptionIndex: 1,
    explanation: 'Hizmetler üretildiği an tüketilir, stoklanamaz. Satılmayan odanın geliri sonsuza dek kaybedilir.',
  ),

  // ÜNİTE 2: KONUK GİRİŞ HAZIRLIĞI (15 Soru)
  QuizQuestion(id: 'kgc10_2_1', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'O gün otele giriş (check-in) yapması beklenen tüm misafirlerin adlarını, oda tiplerini ve özel isteklerini gösteren temel listeye ne denir?',
    options: ['Expected Departure List', 'Expected Arrival List (Günlük Geliş Listesi)', 'Blacklist', 'Lost & Found Defteri'],
    correctOptionIndex: 1,
    explanation: 'Giriş yapacak misafirlerin takibi Expected Arrival List (Günlük Geliş Listesi) ile sağlanır.',
  ),
  QuizQuestion(id: 'kgc10_2_2', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'VIP veya sürekli gelen sadık misafirlerin (Repeat Guest) giriş gününde yapılması gereken en önemli hazırlık nedir?',
    options: ['Oda fiyatına zam yapmak', 'Odalarının saatler öncesinden hazırlanıp kontrol edilmesi ve VIP ikramlarının yerleştirilmesi', 'Odaya hiç kart kodlamamak', 'Sadece çıkış saatini beklemek'],
    correctOptionIndex: 1,
    explanation: 'Özel konukların odaları gelmeden önce hazırlanmalı, ikramlar yerleştirilmeli ve şef tarafından kontrol edilmelidir.',
  ),
  QuizQuestion(id: 'kgc10_2_3', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'Giriş yapacak misafirlerin özelliklerine ve taleplerine göre, otele gelmeden önce oda numarasının sistemde ayrılması işlemine ne denir?',
    options: ['No-Show', 'Blokaj (Oda Atama)', 'Voucher Kontrolü', 'Check-out'],
    correctOptionIndex: 1,
    explanation: 'Oda numaralarının misafirin gelişinden önce rezerve edilip kilitlenmesine Blokaj denir.',
  ),
  QuizQuestion(id: 'kgc10_2_4', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'Blokaj işlemi yapılırken asansör yanı gibi gürültülü olabilecek odalar öncelikle hangi misafir grubuna atanmamalıdır?',
    options: ['1 gece kalacak iş insanlarına', 'Uzun süreli konaklayacak veya balayı tatili yapacak misafirlere', 'Walk-in gelen tek kişilik misafirlere', 'Grup halinde gelen öğrencilere'],
    correctOptionIndex: 1,
    explanation: 'Uzun konaklayacak misafirlerin konforu için sessiz, asansörden uzak ve ferah odalar bloke edilmelidir.',
  ),
  QuizQuestion(id: 'kgc10_2_5', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'Ön büro bilgisayarındaki oda kodu (Örn: Boş Temiz) ile Kat Hizmetlerinin fiili oda denetim raporu arasındaki farka ne ad verilir?',
    options: ['Room Discrepancy (Oda Durum Uyuşmazlığı)', 'Overbooking', 'Stop Sales', 'Lost & Found'],
    correctOptionIndex: 0,
    explanation: 'Sistem kodu ile fiili temizlik durumunun tutmaması durumuna Room Discrepancy (Uyuşmazlık) denir.',
  ),
  QuizQuestion(id: 'kgc10_2_6', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'Oda durum kodlarından "VD" (Vacant Dirty) neyi ifade eder?',
    options: ['Dolu Temiz', 'Boş Kirli', 'Arızalı Oda', 'Boş Temiz'],
    correctOptionIndex: 1,
    explanation: 'Vacant Dirty (VD), odanın boş olduğunu ancak henüz temizlenmediğini belirtir.',
  ),
  QuizQuestion(id: 'kgc10_2_7', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'Oda durum kodlarından "VC" (Vacant Clean) neyi ifade eder?',
    options: ['Dolu Kirli', 'Boş Kirli', 'Boş Temiz (Satışa Hazır)', 'Arızalı Oda'],
    correctOptionIndex: 2,
    explanation: 'Vacant Clean (VC), odanın boş, temizlenmiş, denetlenmiş ve satışa hazır olduğunu gösterir.',
  ),
  QuizQuestion(id: 'kgc10_2_8', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'Otelde teknik veya fiziksel bir arıza nedeniyle satılamayacak durumda olan odalara hangi statü verilir?',
    options: ['VD (Vacant Dirty)', 'VC (Vacant Clean)', 'OO (Out of Order / Arızalı)', 'OC (Occupied Clean)'],
    correctOptionIndex: 2,
    explanation: 'Arızalı ve satış dışı olan odalar sistemde Out of Order (OO) olarak işaretlenir.',
  ),
  QuizQuestion(id: 'kgc10_2_9', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'Oda durum uyuşmazlığı (Room Discrepancy) saptandığında ön büronun atması gereken ilk adım nedir?',
    options: ['Odayı hemen yeni bir misafire satmak', 'Fiziksel kontrol için bellboy veya resepsiyon şefi yönlendirip durumu raporlamak', 'Kat Hizmetleri çalışanlarını cezalandırmak', 'Sistemi görmezden gelmek'],
    correctOptionIndex: 1,
    explanation: 'Uyuşmazlık durumunda odaya fiilen gidilerek bavul veya konuk kontrolü yapılmalı ve sistem güncellenmelidir.',
  ),
  QuizQuestion(id: 'kgc10_2_10', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'Geliş listesinde "kuş tüyü yastık alerjisi var" notu olan bir misafir için ön büro hangi departmanla iş birliği yapmalıdır?',
    options: ['Satın Alma', 'Kat Hizmetleri (Housekeeping)', 'Mutfak', 'Güvenlik'],
    correctOptionIndex: 1,
    explanation: 'Oda içi yastık, çarşaf değişimleri ve oda hazırlığı Kat Hizmetleri departmanı tarafından koordine edilir.',
  ),
  QuizQuestion(id: 'kgc10_2_11', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'Otelcilikte plansız ve hatalı yapılan blokaj (oda atama) işlemlerinin en olası sonucu nedir?',
    options: ['Oda fiyatlarının düşmesi', 'Misafir şikayetleri, oda uyuşmazlıkları ve operasyonel karmaşa', 'Daha fazla bahşiş gelmesi', 'Kat ofislerinin kilitlenmesi'],
    correctOptionIndex: 1,
    explanation: 'Hatalı atamalar misafiri yanlış odaya göndermeye veya dolu odaya anahtar vermeye yol açabilir.',
  ),
  QuizQuestion(id: 'kgc10_2_12', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'Misafirin çıkış yaptıktan sonra yeni misafir gelmeden önce odanın durum kodunun geçmesi gereken doğru evre hangisidir?',
    options: ['VC -> VD', 'VD -> VC', 'OO -> OC', 'OD -> VD'],
    correctOptionIndex: 1,
    explanation: 'Çıkış yapan oda kirli (VD) olur. Kat hizmetleri temizleyince boş temiz (VC) durumuna geçer.',
  ),
  QuizQuestion(id: 'kgc10_2_13', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'Otele giriş yapacak engelli bir konuk için oda bloke edilirken en uygun yerleşim yeri neresidir?',
    options: ['Asansöre yakın, engelli dostu banyolu giriş kat odaları', 'En üst kattaki teraslı süit oda', 'Koridor sonundaki dar kapılı oda', 'Bodrum kattaki personel odası'],
    correctOptionIndex: 0,
    explanation: 'Engelli misafirlerin tahliyesi ve konforu için engelsiz, asansöre yakın ve özel tasarlanmış odalar seçilir.',
  ),
  QuizQuestion(id: 'kgc10_2_14', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'Kat Hizmetleri (Housekeeping) şefinin her gün hazırladığı ve ön büronun uyuşmazlık kontrolünde kullandığı resmi rapor hangisidir?',
    options: ['Voucher Raporu', 'Forecast Cetveli', 'Housekeeping Raporu', 'No-Show Listesi'],
    correctOptionIndex: 2,
    explanation: 'Kat hizmetlerinin fiili oda durumunu gösteren rapora Housekeeping Raporu denir.',
  ),
  QuizQuestion(id: 'kgc10_2_15', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 1,
    questionText: 'Balayı çiftinin geleceği gün "balayı ikramının" odada hazır bulunmaması hangi iki departman arasındaki kopukluktan kaynaklanır?',
    options: ['Ön Büro ve Kat Hizmetleri', 'Satın Alma ve Teknik Servis', 'Güvenlik ve Muhasebe', 'Mutfak ve İnsan Kaynakları'],
    correctOptionIndex: 0,
    explanation: 'Oda içi süsleme and ikram hazırlığı Ön Büro bildirimine göre Kat Hizmetleri ve F&B koordinasyonuyla yapılır.',
  ),

  // ÜNİTE 3: KONUK GİRİŞ (CHECK IN) İŞLEMLERİ (15 Soru)
  QuizQuestion(id: 'kgc10_3_1', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Giriş yapan misafirin kimlik bilgilerini, adresini ve imzasını alarak otelle konuk arasındaki yasal sözleşmeyi başlatan belge hangisidir?',
    options: ['Voucher', 'Registration Card (Kayıt Formu)', 'Forecast Tablosu', 'Folio Dökümü'],
    correctOptionIndex: 1,
    explanation: 'Girişte misafirin imzasıyla doldurulan yasal sözleşme belgesi Registration Card (Kayıt Kartı)\'dır.',
  ),
  QuizQuestion(id: 'kgc10_3_2', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: '1774 Sayılı Kanun gereğince, otele giriş yapan tüm konukların kimlik bilgilerinin gönderildiği resmi sistem hangisidir?',
    options: ['KBS (Kimlik Bildirim Sistemi)', 'TÜRSAB Portalı', 'E-Devlet Arayüzü', 'Merkez Bankası Sistemi'],
    correctOptionIndex: 0,
    explanation: 'Emniyet Genel Müdürlüğü\'ne bağlı Kimlik Bildirim Sistemi (KBS) ile yasal bildirimler anlık yapılır.',
  ),
  QuizQuestion(id: 'kgc10_3_3', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Giriş anında rezervasyonu garanti altında olmayan veya kapıdan gelen konuklardan gelebilecek ekstra harcamalar için alınan teminata ne denir?',
    options: ['Voucher', 'Nakit Depozito', 'Komisyon', 'Kalandır'],
    correctOptionIndex: 1,
    explanation: 'Girişte ekstralar için nakit olarak alınan güvence bedeline Depozito denir ve makbuzu kesilir.',
  ),
  QuizQuestion(id: 'kgc10_3_4', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Giriş esnasında misafirin kredi kartından konaklama ve ekstra harcamaları kapsayacak bir tutarın banka kanalıyla geçici bloke edilmesine ne denir?',
    options: ['Fatura Kesme', 'Pre-Authorization (Ön Provizyon)', 'City Ledger Aktarımı', 'Stop Sales'],
    correctOptionIndex: 1,
    explanation: 'Kredi kartından limit bloke etme işlemine Ön Provizyon (Pre-Authorization) denir.',
  ),
  QuizQuestion(id: 'kgc10_3_5', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Seyahat acentesi vasıtasıyla gelen misafirlerin getirdiği, ödemenin acente tarafından yapılacağını belirten resmi kupon belge hangisidir?',
    options: ['Registration Card', 'Voucher (Acente Belgesi)', 'Adisyon', 'KBS Formu'],
    correctOptionIndex: 1,
    explanation: 'Acentenin misafir adına düzenlediği ödeme belgesine Voucher denir; girişte teslim alınır.',
  ),
  QuizQuestion(id: 'kgc10_3_6', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Giriş işlemleri biten misafirin oda kartının kapıyı açacak şekilde şifrelenmesinde kullanılan cihaz hangisidir?',
    options: ['Encoder (Kart Kodlayıcı)', 'Pos Cihazı', 'Tarayıcı (Scanner)', 'Telsiz'],
    correctOptionIndex: 0,
    explanation: 'Kartlara oda numarası ve tarih yetkisi yükleyen şifreleme cihazına Encoder denir.',
  ),
  QuizQuestion(id: 'kgc10_3_7', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Giriş anında resepsiyonistin oda numarasını lobide yüksek sesle telaffuz etmemesi kuralının temel amacı nedir?',
    options: ['Personelin yorulmasını önlemek', 'Misafirin can ve mal güvenliğini (gizlilik hakkı) korumak', 'Otel kurallarını gizlemek', 'Gürültüyü önlemek'],
    correctOptionIndex: 1,
    explanation: 'Oda numarası gizlidir; kötü niyetli kişilerin duymaması için numara sesli söylenmeyip kart kılıfına yazılır.',
  ),
  QuizQuestion(id: 'kgc10_3_8', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Girişte misafirin bagajlarını teslim alıp odaya çıkaran, odayı ve cihazları tanıtan ön büro personeli kimdir?',
    options: ['Kat Görevlisi', 'Bellboy (Bagaj Taşıma Görevlisi)', 'Acente Temsilcisi', 'Meydancı'],
    correctOptionIndex: 1,
    explanation: 'Bavul taşıma and odaya refakat etme görevini Bellboy yerine getirir.',
  ),
  QuizQuestion(id: 'kgc10_3_9', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Acente voucher\'ında "Yarım Pansiyon (HB)" yazan bir misafere verilmesi gereken doğru bilgi hangisidir?',
    options: ['"Sadece oda ücretiniz dahildir efendim."', '"Sabah kahvaltınız ve akşam yemeğiniz fiyata dahildir; ancak gün içindeki içecekleriniz ücrete tabidir" şeklinde açıklama.', '"Tüm yeme-içmeleriniz ve oda servisiniz ücretsizdir efendim."', '"Sadece öğle yemeğiniz ücretsizdir."'],
    correctOptionIndex: 1,
    explanation: 'Half Board (Yarım Pansiyon), oda + kahvaltı + bir ana yemeği kapsar; içecekler ekstradır.',
  ),
  QuizQuestion(id: 'kgc10_3_10', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Kayıt Formu (Registration Card) üzerinde yer alan hangi alan, yasal anlaşmazlıklarda en bağlayıcı kısımdır?',
    options: ['Misafirin doğum yeri', 'Misafirin imzası ve KVKK onay kutusu', 'Misafirin tuttuğu futbol takımı', 'Otel logosunun rengi'],
    correctOptionIndex: 1,
    explanation: 'Islak imza ve veri izni (KVKK), hukuki olarak kayıt formunun en önemli geçerlilik şartıdır.',
  ),
  QuizQuestion(id: 'kgc10_3_11', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Otele giriş yapan misafirlerin kimlik bilgilerinin yasal sürede Emniyet\'in KBS sistemine girilmemesinin cezası nedir?',
    options: ['Hiçbir cezası yoktur.', 'İşletmeye yönelik ağır idari para cezası ve yasal yaptırımlar uygulanması', 'Sadece sözlü uyarı yapılması', 'Odanın geri alınması'],
    correctOptionIndex: 1,
    explanation: '1774 Sayılı kanun gereği kimlik bildirmemenin veya geç bildirmenin ağır idari para cezası vardır.',
  ),
  QuizQuestion(id: 'kgc10_3_12', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Check-in tamamlanıp anahtar teslim edilirken yapılan otel içi hizmet bilgilendirmesinde (info verme) hangisi bulunmaz?',
    options: ['Kahvaltı saatleri ve yeri', 'Otel Wi-Fi bağlantı şifresi', 'Otel hisselerinin borsa değeri', 'SPA ve havuz kullanım saatleri'],
    correctOptionIndex: 2,
    explanation: 'Info vermede misafirin konaklaması boyunca kullanacağı pratik tesis bilgileri sunulur.',
  ),
  QuizQuestion(id: 'kgc10_3_13', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Bellboyun taşıyacağı bagajlara karışıklığı önlemek için taktığı ve üzerinde oda numarasının yazılı olduğu kupona ne denir?',
    options: ['Voucher', 'Bagaj Kartı / Fişi', 'Adisyon', 'Kayıt Kartı'],
    correctOptionIndex: 1,
    explanation: 'Bagaj kartları, valizlerin doğru odaya ulaştırılmasını ve karışmamasını sağlar.',
  ),
  QuizQuestion(id: 'kgc10_3_14', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Kredi kartından alınan ön provizyon (pre-authorization) bloke tutarı ne zaman nihayete erdirilir ve çözülür?',
    options: ['Misafir odaya girer girmez', 'Çıkış (check-out) günü yapılan son ödeme tahsilatıyla hesap kapatılırken', 'Misafir otelden ayrıldıktan bir ay sonra', 'Sistem otomatik olarak hemen siler'],
    correctOptionIndex: 1,
    explanation: 'Ön provizyon blokesi, çıkış günü yapılan kesin ödeme işlemiyle birlikte çözülerek tahsil edilir.',
  ),
  QuizQuestion(id: 'kgc10_3_15', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 2,
    questionText: 'Misafir resepsiyon bankosuna geldiğinde personelin yapması gereken ilk profesyonel davranış hangisidir?',
    options: ['Bilgisayara bakıp bekletmek', 'Güler yüzle göz teması kurmak ve kibarca "Hoş geldiniz" diyerek selamlamak', 'Doğrudan kimlik istemek', 'Fatura kesmeye başlamak'],
    correctOptionIndex: 1,
    explanation: 'Karşılamada tebessüm, göz teması ve sıcak bir selamlaşma ilk izlenim ve memnuniyetin temelidir.',
  ),

  // ÜNİTE 4: KONUK ÇIKIS (CHECK OUT) İŞLEMLERİ (15 Soru)
  QuizQuestion(id: 'kgc10_4_1', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'O gün otelden çıkış (check-out) yapması beklenen tüm odaların listelendiği resmi tabloya ne denir?',
    options: ['Expected Arrival List', 'Expected Departure List (Ayrılış Listesi)', 'Blacklist', 'KBS Raporu'],
    correctOptionIndex: 1,
    explanation: 'Çıkış yapacak odaların takibi Expected Departure List (Günlük Ayrılış Listesi) ile yapılır.',
  ),
  QuizQuestion(id: 'kgc10_4_2', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Otel çıkış saati olan 12:00\'den sonrasına kadar misafirin talebi ve otel müsaitliğine göre verilen ek süreye ne denir?',
    options: ['No-Show', 'Late Check-out (Geç Çıkış)', 'Extension', 'Walk-in'],
    correctOptionIndex: 1,
    explanation: 'Otel çıkış saatinden sonra tanınan ek kalış süresine Late Check-out denir.',
  ),
  QuizQuestion(id: 'kgc10_4_3', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Misafirin otelde kaldığı süre boyunca yaptığı tüm oda, restoran, SPA ve minibar harcamalarının detaylı dökümünü tutan hesaba ne denir?',
    options: ['Voucher', 'Folio (Misafir Cari Hesabı)', 'Adisyon', 'Kayıt Kartı'],
    correctOptionIndex: 1,
    explanation: 'Misafirin konaklama ve ekstra tüm borçlarının toplandığı hesaba Folio denir.',
  ),
  QuizQuestion(id: 'kgc10_4_4', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Çıkış sırasında misafirin tükettiği ancak sisteme yansımamış minibar harcamalarının kaçmasını önlemek için en doğru operasyon nedir?',
    options: ['Misafire hiç sormamak', 'Misafir bankoda fatura beklerken telsizle Kat Hizmetlerine anlık oda kontrolü yaptırmak', 'Minibar kullanımını tamamen yasaklamak', 'Misafiri suçlamak'],
    correctOptionIndex: 1,
    explanation: 'Telsiz yardımıyla Kat Hizmetlerinden oda kontrolü (minibar check) almak kaçakları sıfırlar.',
  ),
  QuizQuestion(id: 'kgc10_4_5', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Misafirin folio hesabındaki borcun nakit veya kredi kartıyla tahsil edilip hesabın sıfırlanması işlemine ne denir?',
    options: ['Folio Kapatma (Hesap Kapatma)', 'Blokaj Çözme', 'Upgrade', 'KBS Bildirimi'],
    correctOptionIndex: 0,
    explanation: 'Borcun tahsil edilerek folio bakiyesinin sıfırlanmasına Folio Kapatma denir.',
  ),
  QuizQuestion(id: 'kgc10_4_6', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Otelde tahsil edilen konaklama ve ekstra harcamaların KDV oranları ve konuk bilgileriyle resmi faturaya dökülüp verilmesine ne denir?',
    options: ['Adisyon Yazımı', 'Resmi Fatura (Invoice) Düzenleme', 'Voucher Makbuzu', 'Blokaj Fişi'],
    correctOptionIndex: 1,
    explanation: 'Yasal tahsilatların resmi olarak belgelenip basılmasına Fatura (Invoice) denir.',
  ),
  QuizQuestion(id: 'kgc10_4_7', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Acente veya şirket misafirlerinin oda faturasının firmanın kredili hesabına aktarılması sürecine ne ad verilir?',
    options: ['No-Show Faturası', 'City Ledger (Siti Lecır) Aktarımı', 'Nakit Tahsilat', 'Lost & Found'],
    correctOptionIndex: 1,
    explanation: 'Kurumsal faturanın firma cari hesabına virman edilmesine City Ledger aktarımı denir.',
  ),
  QuizQuestion(id: 'kgc10_4_8', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Çıkış esnasında kapı kartlarının geri alınması ve sisteme iade edilmesi öncelikle hangi amaçla yapılır?',
    options: ['Kart tasarrufu ve otel oda güvenliğini sağlamak için', 'Kartların rengini değiştirmek için', 'Kartları çöpe atmak için', 'Acentelere satmak için'],
    correctOptionIndex: 0,
    explanation: 'Kartların geri alınması hem çevresel yeniden kullanım sağlar hem de odaya yetkisiz girişleri önler.',
  ),
  QuizQuestion(id: 'kgc10_4_9', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Check-out esnasında misafirden konaklama memnuniyeti hakkında geri bildirim (feedback) almanın otel açısından en büyük faydası nedir?',
    options: ['Maaşları düşürmek', 'Memnuniyeti ölçerek aksaklıkları düzeltmek ve konuğu online yorum sitelerine (Tripadvisor vb.) davet etmek', 'Zaman kaybettirmek', 'Faturayı kabartmak'],
    correctOptionIndex: 1,
    explanation: 'Geri bildirim, hizmet kalitesini iyileştirir ve memnun konukların dijitalde olumlu yorumlar yazmasını sağlar.',
  ),
  QuizQuestion(id: 'kgc10_4_10', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Misafirin valizlerini lobiden veya odasından alarak araca yerleştiren ve iyi yolculuklar dileyen uğurlama personeli kimdir?',
    options: ['Meydancı', 'Bellboy', 'Acente Rehberi', 'Resepsiyonist'],
    correctOptionIndex: 1,
    explanation: 'Misafir bagajlarının taşınması ve araca yerleştirilmesi görevini Bellboy üstlenir.',
  ),
  QuizQuestion(id: 'kgc10_4_11', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Uğurlama esnasında misafire sorulabilecek en profesyonel ve müşteri odaklı soru hangisidir?',
    options: ['"Neden gidiyorsunuz?"', '"Ulaşım için taksi veya transfer ihtiyacınız var mı efendim?"', '"Otelimizi beğendiniz mi?"', '"Bahşiş bıraktınız mı?"'],
    correctOptionIndex: 1,
    explanation: 'Gidiş transferini veya taksisini sormak, misafirin güvenli ayrılmasını sağlayan profesyonel bir jesttir.',
  ),
  QuizQuestion(id: 'kgc10_4_12', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Resmi faturayı basıp kesmeden hemen önce resepsiyonistin yapması gereken en doğru kontrol nedir?',
    options: ['Hemen yazıcıdan basıp vermek', 'Harcama dökümünü (folio) ekrandan gösterip "Hesabınızda herhangi bir hata var mı efendim?" teyidini almak', 'Misafire hiç göstermemek', 'Sadece oda fiyatını sormak'],
    correctOptionIndex: 1,
    explanation: 'Mali fatura basıldıktan sonra iptal etmek zordur; basılmadan önce mutlaka konuk onayı alınmalıdır.',
  ),
  QuizQuestion(id: 'kgc10_4_13', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Şirket misafirinin şahsi ekstra harcamalarının yanlışlıkla şirket faturasına yansıtılıp reddedilmesini önlemek için girişte ne yapılmalıdır?',
    options: ['Fatura talimatına (billing instruction) eksiksiz ve tam olarak uyulmalıdır.', 'Tüm fatura şirkete kesilmelidir.', 'Hiç fatura kesilmemelidir.', 'Misafirden ödeme alınmamalıdır.'],
    correctOptionIndex: 0,
    explanation: 'Fatura talimatı, neyin şirket neyin misafir tarafından ödeneceğini belirleyen en kritik operasyon kılavuzudur.',
  ),
  QuizQuestion(id: 'kgc10_4_14', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Otelden ayrılan misafiri uğurlarken söylenebilecek en şık ve profesyonel uğurlama cümlesi hangisidir?',
    options: ['"Güle güle, yine gelin."', '"Bizi tercih ettiğiniz için çok teşekkür ederiz efendim. Tekrar görüşmek dileğiyle, iyi yolculuklar."', '"İşlemleriniz bitti, gidebilirsiniz."', '"Kartınızı verip ayrılın."'],
    correctOptionIndex: 1,
    explanation: 'Nazik, kurumsal ve saygılı bir uğurlama cümlesi otelin prestijini ve misafir bağlılığını pekiştirir.',
  ),
  QuizQuestion(id: 'kgc10_4_15', courseId: 'konuk_giris_cikis_islemleri', unitIndex: 3,
    questionText: 'Otelden çıkış yaparken kaba, soğuk veya ilgisiz bir uğurlamayla karşılaşan misafir üzerinde nasıl bir etki oluşur?',
    options: ['Otel fiyatlarının çok ucuz olduğunu düşünür.', 'Girişteki tüm olumlu deneyimler gölgelenir ve otel hakkında olumsuz bir intiba ve kötü yorum kalır.', 'Fark etmez, misafir hemen unutur.', 'Otelde daha fazla kalmak ister.'],
    correctOptionIndex: 1,
    explanation: 'Son izlenim (uğurlama) tatilin özetidir. Kötü bir uğurlama bütün güzel tatili mahvedebilir.',
  ),
"""

# Let's insert the new questions right before the last closing bracket `];`
last_bracket_idx = content.rfind('];')
if last_bracket_idx == -1:
    print("Error: Could not find '];' in file")
    exit(1)

new_content = content[:last_bracket_idx] + new_questions + content[last_bracket_idx:]

with open(file_path, 'w', encoding='utf-8') as f:
    f.write(new_content)

print("Successfully appended 60 new questions for 'konuk_giris_cikis_islemleri'!")
