import os
import re
import xml.etree.ElementTree as ET
from xml.dom import minidom

data_dir = r"c:\Users\erolm\Desktop\TurizmAkademi\lib\core\data"

episodes = []

for root, dirs, files in os.walk(data_dir):
    for file in files:
        if file.endswith('.dart'):
            filepath = os.path.join(root, file)
            with open(filepath, 'r', encoding='utf-8') as f:
                lines = f.readlines()
            
            current_title = None
            current_unit = None
            
            in_map = False
            for line in lines:
                if "const Map<String, dynamic>" in line or "= {" in line:
                    in_map = True
                    current_title = None
                    current_unit = None
                
                if in_map:
                    title_match = re.search(r'^\s+"title":\s*"([^"]+)"', line)
                    if title_match:
                        current_title = title_match.group(1)
                    
                    unit_match = re.search(r'^\s+"learningUnit":\s*"([^"]+)"', line)
                    if unit_match:
                        current_unit = unit_match.group(1)
                    
                    url_match = re.search(r'^\s+"podcastUrl":\s*"([^"]+)"', line)
                    if url_match:
                        url = url_match.group(1)
                        if current_title and url:
                            episodes.append({
                                'title': current_title,
                                'unit': current_unit or "Eğitim",
                                'url': url
                            })
                        in_map = False

print(f"Total episodes found: {len(episodes)}")

# Generate RSS XML with a slightly different title to bypass Spotify caching
rss = ET.Element("rss", version="2.0")
rss.set("xmlns:itunes", "http://www.itunes.com/dtds/podcast-1.0.dtd")
rss.set("xmlns:content", "http://purl.org/rss/1.0/modules/content/")

channel = ET.SubElement(rss, "channel")

ET.SubElement(channel, "title").text = "Turizm Okulum Ses Kutuphanesi"
ET.SubElement(channel, "link").text = "https://erolmertyurdakul.github.io/turizmokulum-podcasts/"
ET.SubElement(channel, "language").text = "tr"
ET.SubElement(channel, "description").text = "Turizm Okulum, Konaklama ve Seyahat Hizmetleri alanı öğretmeni Erol Mert YURDAKUL tarafından hazırlanmış olan, Turizm Mesleki ve Teknik Anadolu Lisesi öğrencilerinin mesleki gelişimlerinde öğrenme süreçlerini desteklemek için hazırlanmış sesli eğitim içerikleri kütüphanesidir."

author = ET.SubElement(channel, "itunes:author")
author.text = "Erol Mert Yurdakul"

# Add iTunes Owner metadata (Name & Email required by Spotify for validation)
owner = ET.SubElement(channel, "itunes:owner")
ET.SubElement(owner, "itunes:name").text = "Erol Mert Yurdakul"
ET.SubElement(owner, "itunes:email").text = "erolmertyurdakul.turizm@gmail.com"

# Standard editor email
ET.SubElement(channel, "managingEditor").text = "erolmertyurdakul.turizm@gmail.com (Erol Mert Yurdakul)"

image = ET.SubElement(channel, "itunes:image")
image.set("href", "https://erolmertyurdakul.github.io/turizmokulum-podcasts/app_logo.png")

category = ET.SubElement(channel, "itunes:category")
category.set("text", "Education")

ET.SubElement(channel, "itunes:explicit").text = "false"

for idx, ep in enumerate(episodes):
    item = ET.SubElement(channel, "item")
    full_title = f"{ep['unit']}: {ep['title']}" if ep['unit'] else ep['title']
    ET.SubElement(item, "title").text = full_title
    ET.SubElement(item, "description").text = f"{full_title} - Turizm Okulum Sesli Eğitim İçeriği."
    
    # Using a different prefix for GUIDs to avoid duplicates in cache
    guid = ET.SubElement(item, "guid")
    guid.text = f"turizm-okulum-edu-ep-{idx}"
    
    day = 1 + (idx % 28)
    pub_date = ET.SubElement(item, "pubDate")
    pub_date.text = f"Tue, {day:02d} Jul 2026 12:00:00 GMT"
    
    enclosure = ET.SubElement(item, "enclosure")
    enclosure.set("url", ep['url'])
    enclosure.set("length", "10000000")
    enclosure.set("type", "audio/mpeg")

xml_str = ET.tostring(rss, encoding='utf-8')
reparsed = minidom.parseString(xml_str)
pretty_xml = reparsed.toprettyxml(indent="  ")

# Remove empty lines generated by toprettyxml
pretty_xml = os.linesep.join([line for line in pretty_xml.splitlines() if line.strip()])

# Changing output file to turizm_feed.xml
output_file = r"c:\Users\erolm\Desktop\TurizmAkademi\scratch\turizm_feed.xml"
with open(output_file, 'w', encoding='utf-8') as out:
    out.write(pretty_xml)

print(f"Generated RSS feed saved to: {output_file}")
